### ISSUE TITLE
COPY does not handle empty arguments well

### ISSUE THREAD

**Issue by joepvd** [openshift/imagebuilder#181]
```sh
cat <<EOF >Dockerfile
FROM centos
COPY Dockerfile "" /tmp/
RUN ls /
RUN ls /tmp
EOF
imagebuilder .
```
This will create a file `/tmpDockerfile`. in `/` `docker build` ignores the empty string.

Use case: An empty `ARG` variable that could be used to copy extra files in.

**Comment by derekhiggins** [comment]
> This will create a file `/tmpDockerfile`. in `/` `docker build` ignores the empty string.
Just to add to this, `imagebuilder` puts anything in the source directory on the host into / (not limited to Dockerfile)
`docker/podman build` does something similar, but instead puts all the files into /tmp

**Comment by nalind** [comment]
@joeg-pro which version of `docker build` are you testing with?  When I run your reproducer with a file other than `Dockerfile` in the build context directory with 19.03.12 (say, by running `touch NOT-THIS-FILE` first), `docker build` copies it to the destination directory, too, as if the empty quoted value was being treated as `*` rather than being ignored.

**Comment by nalind** [comment]
@derekhiggins Thanks for clearing things up!
